The relationship between the user.php and other models.
michaeltsuro/au-store pull request #1
Opened 2024-03-23 20:33 UTC by William-W-Gray

Finished creating the relationship between the users.php and the other model.

2024-03-24 19:58 UTC, CourtneyFradreck commented
LGTM!

2024-03-25 09:37 UTC, michaeltsuro reviewed
Can you revisit your relationships, a user has one address, may you just make sure they are all correct

2024-03-26 00:00 UTC, William-W-Gray commented
> Can you revisit your relationships, a user has one address, may you just make sure they are all correct

ok sir

2024-03-26 11:59 UTC, icep0ps requested changes
Add the following

- return type to your methods
- PHPDoc block

2024-03-26 11:59 UTC, icep0ps commented on app/Models/User.php
> +
Remove these since you are already in the models namespace

2024-03-26 11:59 UTC, icep0ps commented on app/Models/User.php
> +    }
User can only have one address

2024-04-04 12:10 UTC, closed without merging